### ISSUE TITLE
Consider interactions with real generators

### ISSUE THREAD

**Issue by whitequark** [edef1c/libfringe#72]
They just landed: https://github.com/rust-lang/rust/pull/43076
No idea what we should do with them, maybe nothing

**Comment by edef1c** [comment]
:woman_shrugging: you can't even send values *into* them

**Comment by whitequark** [comment]
Yeah I just read the RFC and meh

**Comment by eddyb** [comment]
The limitations are to advance the (already kind of late) `async fn` without introducing *even more* complexity - take a look at the implementation PR and how much back & forth happened on it.

**Comment by whitequark** [comment]
I'm not really criticizing it so much as lamenting their uselessness for my pet use case. Nothing to worry about
