### ISSUE TITLE
project abandoned?

### ISSUE THREAD

**Issue by alkis** [edef1c/libfringe#74]
This project is quite interesting and perhaps the best implementation of user mode context switch for rust. It seems that development has stalled. If it is, can the README be updated? If not is there some avenue for discussing future direction of this crate?

**Comment by edef1c** [comment]
I'd like to work on libfringe again, but I've been somewhat stalled by my own health issues, and intensely demotivated by not having much in the way of feedback — for me this feels like my weird side project nobody actually uses or gives a shit about.
I only have two things that need to happen for 2.x: unwind-on-drop support needs to be integrated (and we need to figure out the `-C panic=abort` case for that), and or1k support needs to be fixed.

**Comment by alkis** [comment]
Having health problems sucks - sorry to hear that - I wish you better health in the future.

I understand that not having feeback or users is not very motivating. That said the repo has 22 watches and 286 stars which shows that there is definitely relatively large interest for this.

I also think that windows support is necessary for this project to succeed further. I will try to hop on IRC to discuss.

**Comment by whitequark** [comment]
> I also think that windows support is necessary for this project to succeed further.

Please read the README to understand why there is no Windows support. This is not changing.

**Comment by alkis** [comment]
I read the README. @whitequark are you on IRC as well? Perhaps we can discuss it there.

**Comment by whitequark** [comment]
#libfringe at irc.mozilla.org, sure
